import { BrowserWindow, session as electronSession } from 'electron'
import { join } from 'node:path'
import { DATA_DIR } from './deps'
import { writeFile, readFile, rm, stat, mkdir, readdir } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { CookieCaptureEvent, CookieCaptureResult, CookieProfile, CookieStatus } from '../shared/types'

// Cookie dang nhap 100% bang Electron (khong can Python/Playwright).
// -> chay duoc tren MOI may nguoi dung, khong cai them gi.

const LOGIN_PARTITION = 'persist:ltskit-login'
const PROFILE_DIR = join(DATA_DIR, 'cookie-profiles')
const LEGACY_PROFILE = join(PROFILE_DIR, 'legacy.txt')
const INITIALIZED = join(PROFILE_DIR, '.initialized')

export function cookiesPath(): string {
  return join(DATA_DIR, 'cookies.txt')
}

/** Chuyen cookie cua Electron sang dinh dang Netscape (yt-dlp doc duoc). */
function toNetscape(cookies: Electron.Cookie[]): string {
  const lines = ['# Netscape HTTP Cookie File', '# Generated by LTSKit', '']
  for (const c of cookies) {
    let domain = c.domain ?? ''
    if (!domain) continue
    const includeSub = c.hostOnly ? 'FALSE' : 'TRUE'
    if (!c.hostOnly && !domain.startsWith('.')) domain = '.' + domain
    const path = c.path || '/'
    const secure = c.secure ? 'TRUE' : 'FALSE'
    const expiry = c.session || !c.expirationDate ? 0 : Math.floor(c.expirationDate)
    // Tien to #HttpOnly_ cho cookie httpOnly (yt-dlp nhan dien)
    const domainField = c.httpOnly ? `#HttpOnly_${domain}` : domain
    lines.push([domainField, includeSub, path, secure, String(expiry), c.name, c.value].join('\t'))
  }
  return lines.join('\n') + '\n'
}

export function normalizeCookieUrl(value: string): { id: string; label: string; loginUrl: string } | null {
  try {
    const url = new URL(value.trim())
    if (url.protocol !== 'http:' && url.protocol !== 'https:') return null
    const id = url.hostname.toLowerCase().replace(/^www\./, '')
    return id ? { id, label: id, loginUrl: url.toString() } : null
  } catch { return null }
}

export function mergeNetscapeCookies(texts: string[]): string {
  const lines = new Map<string, string>()
  for (const text of texts) for (const line of text.split(/\r?\n/)) {
    if (!line.trim() || line.startsWith('#') && !line.startsWith('#HttpOnly_')) continue
    const fields = line.replace(/^#HttpOnly_/, '').split('\t')
    if (fields.length >= 7) lines.set(`${fields[0]}\t${fields[2]}\t${fields[5]}`, line)
  }
  return ['# Netscape HTTP Cookie File', '# Generated by LTSKit', '', ...lines.values(), ''].join('\n')
}

function profilePath(id: string): string { return join(PROFILE_DIR, `${id}.txt`) }
async function initializeProfiles(): Promise<void> {
  await mkdir(PROFILE_DIR, { recursive: true })
  if (existsSync(INITIALIZED)) return
  if (existsSync(cookiesPath())) await writeFile(LEGACY_PROFILE, await readFile(cookiesPath(), 'utf8'), 'utf8')
  await writeFile(INITIALIZED, '', 'utf8')
}
export async function cookieProfiles(): Promise<CookieProfile[]> {
  await initializeProfiles()
  const out: CookieProfile[] = []
  try {
    for (const file of await readdir(PROFILE_DIR)) if (file.endsWith('.txt')) {
      const id = file.slice(0, -4); const text = await readFile(join(PROFILE_DIR, file), 'utf8')
      const count = text.split(/\r?\n/).filter((l) => l.trim() && !l.startsWith('#')).length
      if (count) out.push(id === 'legacy'
        ? { id, kind: 'legacy', label: 'Cookie web đã lưu', loginUrl: '', count }
        : { id, kind: 'web', label: id, loginUrl: `https://${id}`, count })
    }
  } catch { /* no profiles */ }
  return out
}
export async function renderCookies(): Promise<string | null> {
  await initializeProfiles()
  const parts: string[] = []
  try { for (const file of await readdir(PROFILE_DIR)) if (file.endsWith('.txt')) parts.push(await readFile(join(PROFILE_DIR, file), 'utf8')) } catch { /* no profiles */ }
  if (!parts.length) return null
  await writeFile(cookiesPath(), mergeNetscapeCookies(parts), 'utf8')
  return cookiesPath()
}
export async function clearCookieProfile(id: string): Promise<void> {
  if (id === 'legacy') { await rm(LEGACY_PROFILE, { force: true }); await renderCookies(); return }
  await rm(profilePath(id), { force: true })
  try { await electronSession.fromPartition(`persist:ltskit-login-${id}`).clearStorageData({ storages: ['cookies'] }) } catch { /* ignore */ }
}

/**
 * Mo cua so dang nhap (Electron). Nguoi dung dang nhap roi DONG cua so ->
 * doc cookie tu session va ghi ra cookies.txt.
 */
export function captureCookies(
  url: string,
  onEvent: (e: CookieCaptureEvent) => void
): Promise<CookieCaptureResult> {
  return new Promise<CookieCaptureResult>((resolve) => {
    const profile = normalizeCookieUrl(url)
    if (!profile) return resolve({ ok: false, count: 0, path: null, error: 'URL đăng nhập không hợp lệ.' })
    const ses = electronSession.fromPartition(`persist:ltskit-login-${profile.id}`)
    const target = profile.loginUrl

    const win = new BrowserWindow({
      width: 1000,
      height: 720,
      title: 'Dang nhap — LTSKit',
      autoHideMenuBar: true,
      webPreferences: {
        partition: `persist:ltskit-login-${profile.id}`,
        sandbox: true,
        contextIsolation: true,
        nodeIntegration: false
      }
    })

    // Cho phep popup dang nhap (OAuth Google...) mo trong cung session
    win.webContents.setWindowOpenHandler(() => ({ action: 'allow' }))

    onEvent({ phase: 'launching', message: 'Đang mở cửa sổ đăng nhập…' })

    let announced = false
    win.webContents.on('did-finish-load', () => {
      if (!announced) {
        announced = true
        onEvent({
          phase: 'ready',
          message: 'Hãy đăng nhập, rồi ĐÓNG cửa sổ này để lưu cookie.'
        })
      }
    })

    win.loadURL(target).catch(() => {
      /* mot so trang chan navigation truc tiep; van cho nguoi dung thao tac */
    })

    let settled = false
    win.on('closed', () => {
      if (settled) return
      settled = true
      void (async () => {
        try {
          const cookies = await ses.cookies.get({})
           await initializeProfiles()
           await writeFile(profilePath(profile.id), toNetscape(cookies), 'utf-8')
           await renderCookies()
          onEvent({ phase: 'saved', message: `Đã lưu ${cookies.length} cookie.`, count: cookies.length })
          resolve({ ok: true, count: cookies.length, path: cookiesPath(), error: null })
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err)
          onEvent({ phase: 'error', message: msg })
          resolve({ ok: false, count: 0, path: null, error: msg })
        }
      })()
    })
  })
}

export async function cookieStatus(): Promise<CookieStatus> {
  const path = cookiesPath()
  if (!existsSync(path)) return { has: false, path, count: 0 }
  try {
    const s = await stat(path)
    if (s.size === 0) return { has: false, path, count: 0 }
    const text = await readFile(path, 'utf-8')
    const count = text.split(/\r?\n/).filter((l) => l.trim() && !l.startsWith('#')).length
    return { has: count > 0, path, count }
  } catch {
    return { has: false, path, count: 0 }
  }
}

export async function clearCookies(): Promise<void> {
  await rm(cookiesPath(), { force: true })
  // Dang xuat that su: xoa cookie trong session dang nhap
  try {
    await electronSession.fromPartition(LOGIN_PARTITION).clearStorageData({ storages: ['cookies'] })
  } catch {
    /* bo qua */
  }
}
